from typing import TypedDict, List, Optional

class AgentState(TypedDict, total=False):
    ticket: dict
    repo_id: Optional[str]
    commit_sha: Optional[str]
    base_repo_path: Optional[str]
    repo_path: Optional[str]
    workspace_path: Optional[str]
    bug_type: Optional[str]
    keywords: Optional[List[str]]
    likely_files: Optional[List[str]]
    service: Optional[str]
    confidence: Optional[float]
    root_cause_hint: Optional[str]
    failure_signals: Optional[dict]
    retrieval_context: Optional[dict]
    retrieved_files: Optional[List[dict]]
    retrieved_code: Optional[str]
    validation_context: Optional[dict]
    validation_plan: Optional[dict]
    repo_state: Optional[dict]
    repo_profile: Optional[dict]
    symbol_graph_summary: Optional[dict]
    remote_signals: Optional[dict]
    fix: Optional[dict]
    patch_result: Optional[dict]
    sandbox_result: Optional[dict]
    promotion_result: Optional[dict]
    pr_result: Optional[dict]
    pr_status: Optional[str]
    pr_error: Optional[str]
    retry_feedback: Optional[str]
    retry_context: Optional[dict]
    fix_attempt: Optional[int]
    retry_category: Optional[str]
    error: Optional[str]
    status: Optional[str]
